language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm test
#  - npm run build
#deploy:
#  provider: surge
#  skip_cleanup: true
#  domain: <my_name_here>.surge.sh
#  project: ./build/
on:
  branch: master
